kind: Deployment
apiVersion: apps/v1
metadata:
  name: coming-website-v2
  namespace: prod
  labels:
    app: coming-website-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coming-website-v2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coming-website-v2
    spec:
      containers:
        - name: container-coming-website-v2-prod
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          ports:
            - name: http-main
              containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600